Repository UnBArqDsw2020-2/2020.2_G5_EasyCoffee, pull requests merged in 2021-02, with the labels that each got.

#17 05 storyboard
  docs/_sidebar.md
  docs/entrega1/desing_sprint/Storyboard.md
  docs/img/StoryBoard_Cafeteria.png
  docs/img/StoryBoard_Cliente.png
Labels: documentation

#18 Padronização do Storyboard
  docs/entrega1/desing_sprint/Storyboard.md
Labels: documentation

#19 Adicionando mapa mental
  docs/_sidebar.md
  docs/entrega1/desing_sprint/mapa_mental.md
  docs/img/Mapa_mental.jpg
Labels: Design Sprint, documentation, enhancement

#20 14 glossario lexico
  docs/_sidebar.md
  docs/entrega1/lexico.md
  docs/img/lexico/cafe_arabica.jpg
  docs/img/lexico/cafe_robusta.png
  docs/img/lexico/cafeteira.jpg
  docs/img/lexico/coador.jpg
  docs/img/lexico/filtros.jpg
  docs/img/lexico/moedor_eletrico.jpg
  docs/img/lexico/moedor_manual.jpg
  docs/img/lexico/xicara_de_cafe.JPG
  docs/lexico.md
Labels: artefato, documentation

#23 Criando a primeira versão do Guia de Estilo
  docs/_sidebar.md
  docs/entrega1/guia_de_estilo.md
  docs/img/CollorScheme.png
  docs/img/LogoEasyCoffeeV1.2.png
  docs/img/LogoEasyCoffeeV1.2SemFundo.png
  docs/img/guia_de_estilo/button.png
  docs/img/guia_de_estilo/clicked_button.png
  docs/img/guia_de_estilo/other_button.png
Labels: artefato, documentation

#27 #9 #29 Mudança na politica de commit e creiação do 5W2H
  docs/_sidebar.md
  docs/entrega1/5w2h.md
  docs/politicas/politica_de_commits.md
Labels: documentation

#28 6 prototipo
  docs/_sidebar.md
  docs/entrega1/prototipo.md
  docs/img/ScreenshotPrototipo1.png
  docs/img/ScreenshotPrototipo2.png
  docs/img/ScreenshotPrototipo3.png
  docs/img/ScreenshotPrototipo4.png
  docs/img/ScreenshotPrototipo5.png
Labels: Design Sprint, artefato, documentation

#29 2 brainstorm
  docs/_sidebar.md
  docs/entrega1/desing_sprint/brainstorm.md
  docs/entrega1/desing_sprint/design_sprint.md
  docs/img/Brainstorm1.jpg
  docs/img/Brainstorm2.jpg
Labels: Design Sprint, artefato, documentation

#30 [DOC15] Plano de Riscos
  docs/_sidebar.md
  docs/entrega1/plano_de_riscos.md
  docs/img/plano_de_riscos/easy_coffee_EAR.png
Labels: documentation

#31 4 rich picture
  docs/_sidebar.md
  docs/entrega1/desing_sprint/rich_picture.md
  docs/img/RichPictureDanilo.png
  docs/img/RichPictureGabi.jpg
  docs/img/RichPictureGeral.png
  docs/img/RichPictureGustavo.jpg
  docs/img/RichPictureIago.jpg
  docs/img/RichPictureItalo.png
  docs/img/RichPictureMaicon.png
  docs/img/RichPictureRafael.png
Labels: Design Sprint, artefato, documentation

#32 10 diagrama de ishikawa
  docs/_sidebar.md
  docs/entrega1/diagrama_de_ishikawa.md
  docs/img/diagrama_de_ishikawa/diagrama_de_ishikawa.png
Labels: Design Sprint, artefato, documentation

#36 Primeira versão das estimativas de custo do projeto
  docs/_sidebar.md
  docs/entrega1/estimativa.md
Labels: artefato, documentation

#37 Criação do documento de visão
  docs/_sidebar.md
  docs/entrega1/documento_de_visao.md
Labels: artefato, documentation

#38 33 metodologia
  docs/_sidebar.md
  docs/entrega1/metodologia.md
Labels: documentation

#39 Criação da primeira versão do backlog do produto
  docs/_sidebar.md
  docs/entrega1/backlog.md
Labels: artefato, documentation

#40 7 questionario
  docs/_sidebar.md
  docs/entrega1/img/Respostas1.png
  docs/entrega1/img/Respostas10.png
  docs/entrega1/img/Respostas11.png
  docs/entrega1/img/Respostas12.png
  docs/entrega1/img/Respostas13.png
  docs/entrega1/img/Respostas2.png
  docs/entrega1/img/Respostas3.png
  docs/entrega1/img/Respostas4.png
  docs/entrega1/img/Respostas5.png
  docs/entrega1/img/Respostas6.png
  docs/entrega1/img/Respostas7.png
  docs/entrega1/img/Respostas8.png
  docs/entrega1/img/Respostas9.png
  docs/entrega1/img/questionario_parte_1.jpeg
  docs/entrega1/img/questionario_parte_2.jpeg
  docs/entrega1/questionario.md
Labels: Design Sprint, artefato, documentation

#41 Criação do modelo BPMN
  docs/_sidebar.md
  docs/entrega1/bpmn.md
  docs/entrega1/img/scrum.jpg
  docs/entrega1/img/sprint.jpg
  docs/entrega1/img/sprint_planning.jpg
Labels: documentation

#42 Criação do documento requisitos
  docs/_sidebar.md
  docs/entrega1/requisitos.md
Labels: documentation
