Repository UnBArqDsw2020-2/2020.2_G5_EasyCoffee, pull requests merged in 2021-03, with the labels that each got.

#54 [DOC] Diagrama de Atividades
  docs/_sidebar.md
  docs/entrega2/diagramas_uml/diagrama_de_atividades.md
  docs/img/uml/Diagrama_de_Atividades_EasyCoffee(Administrador).png
  docs/img/uml/Diagrama_de_Atividades_EasyCoffee(Cliente).png
Labels: documentation

#63 59 refatoracao metodologia
  docs/entrega1/metodologia.md
Labels: documentation

#64 #57 Refatorando a escrita dos impactos
  docs/entrega1/lexico.md
Labels: artefato, documentation, refatoração

#66 45 diagrama de componentes
  docs/_sidebar.md
  docs/entrega2/diagramas_uml/diagrama_de_componentes.md
  docs/img/uml/diagrama_de_componentes.png
Labels: artefato, documentation, modelagem

#67 Alteração do protótipo para o figma - versão 2.0
  docs/entrega1/prototipo.md
Labels: refatoração

#68 diagrama de estados - caso de compra e login
  docs/entrega2/diagramas_uml/diagrama_de_estados.md
  docs/entrega2/diagramas_uml/diagrama_de_pacotes.md
  docs/entrega2/img/diagrama_estados.png
  docs/entrega2/img/login_DE.png
Labels: artefato, documentation

#69 Diagrama de comunicacao
  docs/_sidebar.md
  docs/entrega2/diagramas_uml/diagrama_de_comunicacao.md
  docs/img/uml/Diagrama_de_Comunicacao(Funcionario).png
  docs/img/uml/Diagrama_de_Comunicacao.png
Labels: documentation

#71 43 diagrama de classe
  docs/_sidebar.md
  docs/entrega2/diagramas_uml/diagrama_de_classe.md
  docs/entrega2/diagramas_uml/diagrama_de_pacotes.md
  docs/img/diagrama_classe/Diagrma_de_Classev1.jpg
  docs/img/uml/Diagrama_de_Classes_v1.0.png
  docs/index.html
Labels: documentation

#73 61 refatoracao backlog do produto
  docs/_sidebar.md
  docs/entrega2/backlog_entrega2.md
Labels: documentation

#74 46 diagrama de sequencia
  docs/_sidebar.md
  docs/entrega2/diagramas_uml/diagrama_de_sequencia.md
  docs/img/uml/Diagrama_sequencia_administrador_manter_glossario.png
  docs/img/uml/Diagrama_sequencia_administrador_manter_produto.png
  docs/img/uml/Diagrama_sequencia_compras_cliente.png
  docs/img/uml/Diagrama_sequencia_manter_cliente.png
Labels: documentation

#75 Adicionando os requisitos não funcionais e NFRs
  docs/_sidebar.md
  docs/entrega1/img/NFR/NFR_Confiabilidade.jpg
  docs/entrega1/img/NFR/NFR_Seguranca.jpg
  docs/entrega1/img/NFR/NFR_desempenho.png
  docs/entrega1/img/NFR/NFR_portabilidade.jpg
  docs/entrega1/img/NFR/NFR_usabilidade.jpg
  docs/entrega1/requisitos.md
  docs/entrega1/requisitos_nao_funcionais.md
Labels: artefato, documentation

#77 refatoracao requisitos
  docs/entrega1/img/NFR/diagrama_desempenho(propagacao).jpg
  docs/entrega1/img/NFR/diagrama_desempenho_nfr.jpg
  docs/entrega1/img/NFR/diagrama_nfr_confiabilidade(propagacao).png
  docs/entrega1/img/NFR/diagrama_nfr_usabilidade(propagacao).png
  docs/entrega1/img/NFR/diagrama_portabilidade_nfr(propagacao).png
  docs/entrega1/img/NFR/diagrama_seguranca_nfr(propagacao).png
  docs/entrega1/requisitos_nao_funcionais.md
Labels: artefato, documentation
